-- File Transfer Database Tables Creation Script
-- Database: file_transfer_db
-- Execute this script in your MySQL database

USE file_transfer_db;

-- Table 1: file_transfer_data_source
CREATE TABLE IF NOT EXISTS file_transfer_data_source (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_SOURCE VARCHAR(255) NULL,
    ACTIVE INT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table 2: file_transfer_folder_path
CREATE TABLE IF NOT EXISTS file_transfer_folder_path (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_SOURCE_ID INT NULL,
    ENVIRONMENT VARCHAR(255) NULL,
    FOLDER_PATH TEXT NULL,
    SITE VARCHAR(255) NULL,
    ACTIVE INT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_data_source_id (DATA_SOURCE_ID),
    INDEX idx_environment (ENVIRONMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table 3: file_transfer_setting
CREATE TABLE IF NOT EXISTS file_transfer_setting (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(255) NULL,
    VALUE VARCHAR(255) NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_type (TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table 4: file_transfer_zip_tracking
CREATE TABLE IF NOT EXISTS file_transfer_zip_tracking (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FINAL_ZIP_NAME VARCHAR(500) NOT NULL,
    DATA_SOURCE VARCHAR(100) NOT NULL,
    ENVIRONMENT VARCHAR(50) NOT NULL,
    SOURCE_FOLDER_PATHS JSON NULL,
    FILES_INFO JSON NULL,
    ZIP_SIZE_BYTES BIGINT NULL,
    TOTAL_FILES_COUNT INT NULL,
    CREATED_TIMESTAMP DATETIME NOT NULL,
    BACKUP_PATH VARCHAR(1000) NULL,
    UPLOADED_TO_DATALAKE TINYINT(1) NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_final_zip_name (FINAL_ZIP_NAME),
    INDEX idx_data_source (DATA_SOURCE),
    INDEX idx_environment (ENVIRONMENT),
    INDEX idx_created_timestamp (CREATED_TIMESTAMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table 5: file_transfer_error_log
CREATE TABLE IF NOT EXISTS file_transfer_error_log (
    ID VARCHAR(255) PRIMARY KEY,
    ENVIRONMENT VARCHAR(255) NULL,
    DATA_SOURCE VARCHAR(255) NULL,
    ERROR_MESSAGE TEXT NULL,
    FILE_NAME VARCHAR(255) NULL,
    FOLDER_PATH TEXT NULL,
    ORIGINAL_ARCHIVE_FILE_NAME VARCHAR(500) NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOLVED TINYINT(1) DEFAULT 0,
    SOLVED_DATE VARCHAR(255) NULL,
    INDEX idx_environment (ENVIRONMENT),
    INDEX idx_data_source (DATA_SOURCE),
    INDEX idx_solved (SOLVED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Display created tables
SHOW TABLES;
